/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.tsx',
    './index.ts',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Surface
        bg: '#FBF7EE',
        bgSubtle: '#EEE8D8',
        surface: '#F7F2E6',
        surfaceRaised: '#FDFAF3',
        overlay: 'rgba(58, 47, 30, 0.35)',
        // Border
        border: '#E2D9C4',
        borderStrong: '#CEC3A8',
        // Text
        textPrimary: '#3A2F1E',
        textSecondary: '#6B5C44',
        textTertiary: '#9C8B72',
        textDisabled: '#C0AE92',
        textInverse: '#FBF7EE',
        // Interactive
        fillBold: '#3A2F1E',
        fillAccent: '#A07030',
        fillAccentSub: '#FBF5E8',
        // Status
        positive: '#2A6060',
        positiveSub: '#EAF4F2',
        positiveBorder: '#82B8B4',
        negative: '#B83A2A',
        negativeSub: '#FBF0EE',
        negativeBorder: '#DDA090',
        warning: '#A07030',
        warningSub: '#FBF5E8',
        warningBorder: '#C9A86C',
        info: '#5A4A8A',
        infoSub: '#F0EEF9',
        infoBorder: '#AFA9EC',
        highlight: '#A07030',
        highlightSub: '#FBF5E8',
        highlightBorder: '#C9A86C',
        yin: '#5A4A8A',
        yinSub: '#F0EEF9',
        yinBorder: '#AFA9EC',
        yang: '#A07030',
        yangSub: '#FBF5E8',
        yangBorder: '#C9A86C',
        // Ohaeng (for static classes; dynamic use ohaengColors from design-system)
        ohaeng: {
          wood: { base: '#3A6818', light: '#EEF6E8', border: '#A8CC88' },
          fire: { base: '#A03020', light: '#FBF0EE', border: '#DDA090' },
          earth: { base: '#906830', light: '#FDF5E4', border: '#D4B870' },
          metal: { base: '#706050', light: '#F4F2EC', border: '#C0B898' },
          water: { base: '#2A6060', light: '#EAF4F2', border: '#82B8B4' },
        },
      },
      spacing: {
        0: 0,
        '0.5': 2,
        1: 4,
        2: 8,
        3: 12,
        4: 16,
        5: 20,
        6: 24,
        8: 32,
        10: 40,
        12: 48,
        14: 56,
        16: 64,
      },
      borderRadius: {
        sm: 6,
        md: 10,
        lg: 14,
        xl: 20,
        full: 9999,
      },
      fontFamily: {
        serifLight: ['NotoSerifKR_300Light'],
        serif: ['NotoSerifKR_300Light'],
        serifRegular: ['NotoSerifKR_400Regular'],
        serifMedium: ['NotoSerifKR_500Medium'],
        serifSemiBold: ['NotoSerifKR_600SemiBold'],
        sans: ['NotoSansKR_300Light', 'NotoSansKR_400Regular'],
        sansRegular: ['NotoSansKR_400Regular'],
        sansMedium: ['NotoSansKR_500Medium'],
      },
      fontSize: {
        display: [32, { lineHeight: 1.2, letterSpacing: -0.5 }],
        title1: [24, { lineHeight: 1.3, letterSpacing: 2 }],
        title2: [20, { lineHeight: 1.35, letterSpacing: 1 }],
        heading: [16, { lineHeight: 1.4, letterSpacing: 0.5 }],
        numeralLg: [32, { lineHeight: 1, letterSpacing: -1 }],
        numeralMd: [20, { lineHeight: 1, letterSpacing: 0 }],
        hanjaLg: [24, { lineHeight: 1, letterSpacing: 0 }],
        hanjaSm: [16, { lineHeight: 1, letterSpacing: 0 }],
        serifLabel: [13, { lineHeight: 1.4, letterSpacing: 1 }],
        bodyLg: [15, { lineHeight: 1.7, letterSpacing: 0 }],
        body: [13, { lineHeight: 1.7, letterSpacing: 0 }],
        bodySm: [11, { lineHeight: 1.7, letterSpacing: 0 }],
        uiMd: [14, { lineHeight: 1.4, letterSpacing: 0.3 }],
        uiSm: [13, { lineHeight: 1.4, letterSpacing: 0.3 }],
        label: [11, { lineHeight: 1.4, letterSpacing: 0.5 }],
        caption: [10, { lineHeight: 1.5, letterSpacing: 0.5 }],
        overline: [9, { lineHeight: 1.5, letterSpacing: 2 }],
      },
    },
  },
  plugins: [],
  // 변수/동적 className으로 쓰이는 design-system 클래스가 번들에 포함되도록
  safelist: [
    // typography (textClassNames)
    'text-display', 'text-title1', 'text-title2', 'text-heading',
    'text-numeralLg', 'text-numeralMd', 'text-hanjaLg', 'text-hanjaSm', 'text-serifLabel',
    'text-bodyLg', 'text-body', 'text-bodySm', 'text-uiMd', 'text-uiSm', 'text-label', 'text-caption', 'text-overline',
    'font-serif-light', 'font-serif-regular', 'font-serif-medium', 'font-serif-semi-bold',
    'font-sans-regular', 'font-sans-medium', 'uppercase',
    // semantic text colors
    'text-textPrimary', 'text-textSecondary', 'text-textTertiary', 'text-textDisabled', 'text-textInverse',
    // backgrounds / borders
    'bg-bg', 'bg-bgSubtle', 'bg-surface', 'bg-surfaceRaised', 'bg-fillBold', 'bg-border',
    'border-border', 'border-borderStrong', 'border-textSecondary',
  ],
};
